### ISSUE TITLE
Image d'accroche dans l'édition d'un article

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#152]
Quand on choisit d'utiliser une vignette comme image d'accroche, celle-ci est affichée en pleine largeur
sur la page d'édition. Ce n'est pas l'effet attendu pour une vignette.
Cela est imposé par la règle CSS dans le fichier theme.css ligne 504 :
```css
#id_img_thumbnail img { width: 100%; ... }
```
La règle suivante me semble plus pertinente :
```css
#id_img_thumbnail img { max-width: 100%; ... }
```
